### ISSUE TITLE
INA219 very sensitive for external influence

### ISSUE THREAD

**Issue by hogthrob** [thomastech/Sparky#7]
On my build (which is quite similar to the original one), the current readings are easily disturbed by placing or moving a hand close to the INA219 mounted on the perfboard. I use twisted wire but moving the wire around or touching it does not cause changes. 
Also if everything is put together I see more fluctuation in the measured current than if the electronics are not as close to the front of the welder.  However, the disturbuance create by hand movements is worse.

**Comment by thomastech** [comment]
I suggest rechecking the filter modification that was done to your INA219 module. 

- Thomas

**Comment by thomastech** [comment]
@hogthrob  Did you resolve this issue?

**Comment by hogthrob** [comment]
No, I checked the filter modification and it is as per data sheet. You don't have that issue?
My test setup is to use a thick bolt to put ground clamp and stick holder on and turn on current.

**Comment by thomastech** [comment]
On my installation all noise pickup issues went away after installing the INA219 filter; My readings are stable. I'm using two 10 ohm resistors and a .1uF cap. All parts soldered *directly* on the INA219 board.

Maybe your issue is due to a ground loop in Sparky's wiring or your welder's DC inverter is noisier than mine. FWIW, the INA219 has a high impedance input (>300k ohms). So keep the shunt wiring as short as practical. 

If necessary, try adding a termination close to the INA219 chip.  For example, a 1K ohm across the input of the filter circuit (side connected to the shunt). This large value should have no influence to the existing shunt value but might be low enough to reduce some EMI/RFI noise pickup. 

- Thomas
